// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nnmmotmmccndscqjmrbe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ubW1vdG1tY2NuZHNjcWptcmJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzMzc1NDUsImV4cCI6MjA3NDkxMzU0NX0.5UkiOlnb0oQjAR2tdeFbcrfkSFxBaZTtSAhrgyandn4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});